export const STRING = {
    searchPlaceholder: 'Search...',
    becomeATutor: 'Become A Tutor',
    logout: 'logout',
    home: 'Home',
    call: 'Call',
    chat: 'Chat',
    study: 'Study',
    profile: 'Profile',
    requestTutor: 'Request tutor',
    signInTitle: 'Sign In',
    signIn: 'SignIn',
    signUp: 'SignUp',
    filterBy: 'FILTER BY:',
    viewMore: 'View more',
    eventTitle: 'Upcoming events',
    subjectTitle: 'Subjects',
    tutorTitle: 'Tutors',
    forgotPassword: 'Forgot password',
    continueToAcastudy: 'To Continue to Acastudy',
    
    forgotPasswordSubTitle: 'To reset your password, please provide your email address in the field below.',

    bannerTopic: 'Personalised Learning, Anytime, Anywhere',
    bannerContent: `Welcome to Acastudy, where education is tailored to fit your needs! Our platform connects you with expert tutors who are ready to help you achieve academic success. Whether it's a quick session or a scheduled deep dive, Acastudy provides flexible, on-demand learning experiences that adapt to your goals and availability.`,
    bannerSubContent: 'Take control of your academic journey and thrive with Acastudy today!',
    bannerSearchPlaceholder: 'Search for a subject',
    OnbordingBecomeAStudentTittle: 'Become A Student',
    OnbordingBecomeAStudentFirstSubtitle: 'Unlock Your Full Potential with Acastudy',
    OnbordingBecomeAStudentFirstInfo: 'At Acastudy, we provide more than just tutoring—we offer personalized learning experiences designed to help you excel academically and personally. With top-rated tutors, tailored sessions, and a supportive community, we guide you to unlock your true potential.',
    OnbordingBecomeAStudentSecondSubtitle: 'Join us and gain access to:',
    OnbordingBecomeAStudentSecondInfo: 'Customized one-on-one tutoring sessions that inspire growth. Comprehensive study tools and resources at your fingertips. A vibrant community of peers and mentors to support your journey. Take the next step—don\'t just study, Acastudy!',
    OnbordingBecomeAStudentButtonText: 'Sign up as a Student',
    OnbordingBecomeATutor: 'Become A Tutor',
    OnbordingBecomeATutorFirstSubtitle: 'Transform Lives with Your Expertise on Acastudy',
    OnbordingBecomeATutorFirstInfo: 'Are you passionate about teaching? Acastudy provides you with a platform to connect with eager students, earn competitive income, and share your knowledge while growing professionally.',
    OnbordingBecomeATutorSecondSubtitle: 'Earn 70% of session fees.',
    OnbordingBecomeATutorSecondInfo: 'Share your expertise with a wide, motivated audience. Access professional growth opportunities within a supportive community. Start making a difference today.',
    OnbordingBecomeATutorSecondInfoExtraInfo: 'Sign up now as a tutor on Acastudy and empower students with your expertise!',
    OnbordingBecomeATutorButtonText: 'Sign up as a Tutor',
};

export const NAV_SCREEN_NAME = {
    HomeScreen: 'HomeScreen',
    WelcomeScreen: 'WelcomeScreen',
    CallScreen: 'CallScreen',
    ChatScreen: 'ChatScreen',
    ProfileScreen: 'ProfileScreen',
    StudyScreen: 'StudyScreen',

    SignInScreen: 'SignInScreen',
    SignUpScreen: 'SignUpScreen',
    PasswordScreen: 'PasswordScreen',
    ForgotPasswordScreen: 'ForgotPasswordScreen',
    OnboardingScreen: 'OnboardingScreen',
    VerifyEmailScreen: 'VerifyEmailScreen',

    SubjectTopicsScreen: 'SubjectTopicsScreen',
    TutorScreen: 'TutorScreen',
    SubjectScreen: 'SubjectScreen',
    TutorProfileScreen: 'TutorProfileScreen',
    TermsOfUseScreen: 'TermsOfUseScreen',
    PrivacyPolicyScreen: 'PrivacyPolicyScreen',

};

export const DEVICE_TYPE = {
    mobile: 'mobile',
    tablet: 'tablet',
    desktop: 'desktop',
};